### ISSUE TITLE
Remaining Docs

### ISSUE THREAD

**Issue by artalat** [BlueEastCode/bluerain-docs#2]
### Overview

- [ ] 🎡 Lifecycle Events (Y)
- [ ] 🧠 Thinking in BlueBase (Y)
- [ ] ⛩ Main App Layout (Y)
- [ ] 🏋️‍♀️ How BlueBase works (Y)

### Key Concepts

- [ ] 🔀 Navigation (#1) (Y) C
- [ ] 🖼 Assets (Y) 
- [ ] 🔤 Fonts (Y) 

### Guides

- [ ] 🔥 Hot Module Replacement (Y) M
- [ ] 🌏 Server Side Rendering 
- [ ] 🈯️ Internationalisation (Y) M
- [ ] 🚀 GraphQL integration (Y) M
- [ ] 🚨 Error Reporting (Y) M
- [ ] 📈 Analytics (Y) M
- [ ] 🎨 Theming (Y) C
- [ ] ⛑ SEO (Y) C
- [ ] 👮 Security 
- [ ] 🍃 Tree-shaking
- [ ] ⚡️ Progressive Web Apps 
- [ ] 🌅 Splash Screens (Y) M
- [ ] 📱 App Icons (Y) M
- [ ] ⏬ Preloading & Prefetching
- [ ] 📗 App Menus 
- [ ] ⚙️ Settings (Y) M
- [ ] 👩‍💻 Platform Specific Code (Y) M
- [ ] 💄 Styling
- [ ] 🏗 Layouts (Y) C
- [ ] 🍱 JSON Components (Y) M
- [ ] 📲 Grid & Responsive Components (Y) M
- [ ] 🏛 FavIcon (Y) M

### System API

- [ ] ☔️ BlueRain Context

### Component API

- [ ] Button
- [ ] Card
- [ ] ...etc

### CLI

- [ ] Web
- [ ] Electron
- [ ] Expo
- [ ] Storybook
- [ ] Storybook Native

### Plugin Directory
- [ ] Plugins Directory
